# Generated by Django 4.1.7 on 2023-06-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_name_alter_category_slug_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'categories', 'verbose_name_plural': 'categ'},
        ),
    ]
