# Generated by Django 4.1.7 on 2023-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='old_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
