# Generated by Django 4.1.7 on 2023-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_products_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img1',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img2',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='img3',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='imgin',
            field=models.ImageField(default=1, upload_to='products'),
            preserve_default=False,
        ),
    ]
