# Generated by Django 4.1.7 on 2023-06-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products_img1_products_img2_products_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc1',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
